processors_to_run: "0:" 
workspace_dir: ???

processors:
  - _target_: sdp.processors.nemo.beamsearch_inference.BeamsearchTopNInference
    in_memory_chunksize: 10000
    input_manifest_file: /mnt/md1/YTDS/ES/clean_data/es_manifest_no_punct.json
    output_manifest_file: ${workspace_dir}/es_manifest_topn.json
    input_audio_key: audio_filepath
    output_text_key: pred_texts
    batch_size: 64
    device: cuda
    model_path: /mnt/md1/YTDS/ES/lm/stt_es_fastconformer_hybrid_large_pc.nemo


  - _target_: sdp.processors.nemo.beamsearch_inference.RestorePCbyTopN
    output_manifest_file: ${workspace_dir}/es_manifest_restored_punct.json
    text_without_pc_key: text
    texts_with_pc_key: pred_texts
    output_text_key: pred_text
    punctuation: ",.?"
    do_lower: true