processors_to_run: "0:"
workspace_dir: ???
final_manifest: ${workspace_dir}/final_manifest.json

processors:
  - _target_: sdp.processors.CreateInitialManifestMCV # conda install -c conda-forge -y sox libvorbis
    raw_data_dir: ${workspace_dir}
    extract_archive_dir: ${workspace_dir}/row
    resampled_audio_dir: ${workspace_dir}/16k
    data_split: train
    language_id: cv-corpus-15.0-2023-09-08-hy-AM
    output_manifest_file: ${workspace_dir}/manifest0.json

  - _target_: sdp.processors.ASRWhisper
    output_manifest_file: ${workspace_dir}/manifest1.json
    pretrained_model: "large-v2"
    output_text_field: pred_text

  - _target_: sdp.processors.DropHighWER
    text_key: text
    pred_text_key: pred_text
    wer_threshold: 75

  - _target_: sdp.processors.DropHighCER
    output_manifest_file: ${workspace_dir}/manifest3.json
    text_key: text
    pred_text_key: pred_text
    cer_threshold: 30

  - _target_: sdp.processors.ASRTransformer #pip install accelerate
    input_manifest_file: ${workspace_dir}/manifest1.json
    output_manifest_file: ${workspace_dir}/manifest4.json
    pretrained_model: "distil-whisper/distil-large-v2" #"openai/whisper-large-v3"
    output_text_field: pred_text3

  - _target_: sdp.processors.DropHighWER
    text_key: text
    pred_text_key: pred_text3
    wer_threshold: 75

  - _target_: sdp.processors.DropHighCER
    output_manifest_file: ${final_manifest}
    text_key: text
    pred_text_key: pred_text3
    cer_threshold: 30