processors_to_run: "0:"
workspace_dir: /workspace/nemo_capstone
final_manifest: ${workspace_dir}/final_manifest.json

processors:
  - _target_: sdp.processors.CreateInitialManifestytdlp
    raw_data_dir: /workspace/nemo_capstone
    output_field: audio_filepath
    output_manifest_file: ${workspace_dir}/manifest0.json

  - _target_: sdp.processors.GetYoutubeAudio
    links_filepath_field: audio_filepath
    output_audio_path: ${workspace_dir}/audio_files/
    output_manifest_file: ${workspace_dir}/manifest1.json

