documentation: |
  Toloka Armenian

processors_to_run: all
input_manifest: data_test/test_manifest
text_key: text
workspace_dir: ???

processors:
  - _target_: sdp.processors.MakeSentence
    text_key: ${text_key}
    end_symbol: ":"
    make_uppercase: True
    input_manifest_file: ${workspace_dir}/${input_manifest}.json
    # output_manifest_file: ${workspace_dir}/manifest_stage-3.json

  # - _target_: sdp.processors.KeepOnlySpecifiedFields
  #   fields_to_keep: ["text", "audio_filepath", "duration"]
  #   # output_manifest_file: ${workspace_dir}/manifest_stage-2.json

  # - _target_: sdp.processors.GetAudioDuration
  #   audio_filepath_field: audio_filepath
  #   duration_field: duration
  #   # output_manifest_file: ${workspace_dir}/manifest_stage-1.json

  - _target_: sdp.processors.SubRegex
    text_key: ${text_key}
    regex_params_list:
      - {"pattern": '։', "repl": ':'}
      - {"pattern": '․', "repl": "."}
      - {"pattern": '—', "repl": "-"}
      - {"pattern": '–', "repl": "-"}
      - {"pattern": '_', "repl": "-"}
      - {"pattern": '―', "repl": "-"} 
      - {"pattern": '\.\.\.', "repl": "…"}
      - {"pattern": '՝', "repl": "`"}
      - {"pattern": '/', "repl": " "}
      - {"pattern": '\|', "repl": " "}
      - {"pattern": '●', "repl": " "}
      - {"pattern": '~', "repl": ""}
      - {"pattern": '#', "repl": " "}
      - {"pattern": "\\s+", "repl": " "}
    # output_manifest_file: ${workspace_dir}/manifest_stage0.json

  - _target_: sdp.processors.SubRegex
    text_key: ${text_key}
    regex_params_list:
      - {"pattern": ':', "repl": '։'}
      - {"pattern": '-', "repl": "֊"}
      - {"pattern": "`", "repl": "՝"}
      - {"pattern": "ʹ", "repl": "՛"}
      - {"pattern": "´", "repl": "՛"}
      - {"pattern": "《", "repl": "«"}
      - {"pattern": "》", "repl": "»"}  
      - {"pattern": "“", "repl": "«"}
      - {"pattern": "”", "repl": "»"}  
      - {"pattern": "եւ", "repl": "և"}  
      - {"pattern": "\u200b", "repl": ""}
      - {"pattern": "\\s+", "repl": " "} 
    # output_manifest_file: ${workspace_dir}/manifest_stage1.json
      
    
  - _target_: sdp.processors.DropNonAlphabet
    alphabet: "ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖՈՒԵաբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆուև ՛ ՜ ՝ ՞ ։	֊ ՙ ՚ . … « » , ( )"
    output_manifest_file: ${workspace_dir}/${input_manifest}_clear.json
