documentation: |
  Toloka Armenian

processors_to_run: all
workspace_dir: ???
API_KEY: "1V0v8tbFtwPhDVMbN3cvcQ.045e.k93FVRUudCOHplT6OHcDNjc-k8V_rSFr8l5_jLyo4rLT9W4fgabM40EyompNakPZ0uU-_sgc0hKHzrEge5AJNy5MwZCu93BHoTJGOS1lwqE"
# pool_id: 42824822
# pool_id: 42939416
pool_id: 42949209

processors:
  - _target_: tolokan.processors.GetTolokaResults
    input_pool_file: ${workspace_dir}/taskpool.json
    input_data_file: ${workspace_dir}/data_file.json
    status: ACCEPTED
    output_dir: ${workspace_dir}/results
    output_manifest_file: ${workspace_dir}/manifest-1.json
    API_KEY: ${API_KEY}
    platform: "PRODUCTION"
    pool_id: ${pool_id}

  - _target_: sdp.processors.ASRFileCheck
    audio_filepath_key: audio_filepath  
    corrupted_audio_dir: ${workspace_dir}/curr
    output_manifest_file: ${workspace_dir}/manifest0.json

  - _target_: sdp.processors.AudioResampler
    output_manifest_file: ${workspace_dir}/manifest1.json
    resampled_audio_dir: ${workspace_dir}/16k
    audio_filepath_key: "audio_filepath"
    target_samplerate: 16000
    target_nchannels: 1

  # - _target_: sdp.processors.ASRSeamless
  #   input_manifest_file: ${workspace_dir}/result_manifest.json
  #   input_field: audio_filepath
  #   output_field: pred_text
  #   output_manifest_file: ${workspace_dir}/result_manifest_pred.json
  #   limit: 100

  - _target_: sdp.processors.DropIfRegexMatch
    output_manifest_file: ${workspace_dir}/manifest2.json
    text_key: "user_id"
    regex_patterns:
      - "f00a521ecdfae90d3749db2bc94ba47a"
      - "ca29f958eb3aaaf76a91b35b252c2600"
      - "93ff8ebc07a045af2f3d0d9eeaf8cf16"
      - "7d983bd8f5a33ed5fc6402f3b4fb07ae"
      - "8c63c2fbbe67f8863b1153a0d26fcfbc"
      - "975498979917c2475f1b500ecec07364"
      - "725dbe25e01fc14d255e7c59aaa41313"
      - "0a9b8cc44c7f3f18dcae8ae0ab224fb2"
      - "408621c64ddf415f8f17822de91e41f5"
      - "1336f10071ff290c35f0b2ef3cc6d185"
      - "88319c47b41e5977293743cb8a841572"
      - "612bdd7ff7d6c95357d661032cb819a3"
      - "807a2e89c64fd815d3753edd41b8754d"
      - "c1a8633196fabb27454899ea4a88916d"
      - "e3be16058c9898084bbad5282167c7ff"
      - "2b97303bb6dc587988016e130c71bbb5"
      - "86e79eda49665b1810ed07084ca5fe2c"

  - _target_: sdp.processors.MakeSentence
    text_key: "text"
    end_symbol: ":"
    make_uppercase: True
    output_manifest_file: ${workspace_dir}/manifest3.json    

  - _target_: sdp.processors.KeepOnlySpecifiedFields
    output_manifest_file: ${workspace_dir}/manifest4.json
    fields_to_keep: ["text", "audio_filepath"]

  - _target_: sdp.processors.GetAudioDuration
    audio_filepath_field: audio_filepath
    duration_field: duration
    input_manifest_file: ${workspace_dir}/manifest4.json
    output_manifest_file: ${workspace_dir}/evn_mag_manifest_${pool_id}.json


  # - _target_: sdp.processors.SubRegex
  #   output_manifest_file: ${workspace_dir}/evn_mag_manifest_${pool_id}1.json
  #   text_key: text
  #   regex_params_list:
  #     - {"pattern": "«", "repl": ""}
  #     - {"pattern": "»", "repl": ""}

  # - _target_: sdp.processors.GetWER
  #   pred_text_key: model_transcribed_text
  #   output_manifest_file: ${workspace_dir}/result_manifest_pred_clean.json

  # - _target_: sdp.processors.SubMakeLowercase
  #   text_key: text

  # - _target_: sdp.processors.SubRegex
  #   text_key: text
  #   regex_params_list:
  #     - {"pattern": '[^աբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆուև ]', "repl": ""}
  #   output_manifest_file: ${workspace_dir}/evn_mag_manifest_${pool_id}.json

