documentation: |
  Toloka Armenian

processors_to_run: all
workspace_dir: ???
testspace_dir: ${workspace_dir}/texttest
API_KEY: "QBiiuByvLaYu1llgZjDFXw.045e.f1bcUbqp_4Q5ENwt9-_NdCNjZpQspNFAwnm1qXPj-Y24DyjVuxPhP4nu7DKoxuZgiZvvfWalAZ4uIb3o4ztD0kt8jNP4sW4k8tp_8m3JwUQ"

processors:
  - _target_: sdp.processors.CreateInitialManifestByExt
    raw_data_dir: ${workspace_dir}/arm_docs
    extension: docx
    output_field: source_filepath
    output_manifest_file: ${testspace_dir}/docfiles.json

  - _target_: sdp.processors.ReadDocxLines
    source_filepath: source_filepath
    text_key: text
    output_manifest_file: ${testspace_dir}/lines.json

  - _target_: sdp.processors.SubRegex
    input_manifest_file: ${testspace_dir}/lines.json
    output_manifest_file: ${testspace_dir}/lines1.json
    text_key: text
    regex_params_list:
      - {"pattern": '։', "repl": ':'}
      - {"pattern": '․', "repl": "."}
      - {"pattern": '—', "repl": "-"}
      - {"pattern": '–', "repl": "-"}
      - {"pattern": '―', "repl": "-"}
      - {"pattern": '\.\.\.', "repl": "…"}
      - {"pattern": "\\s+", "repl": " "}

  - _target_: sdp.processors.DropIfRegexMatch
    input_manifest_file: ${testspace_dir}/lines1.json
    output_manifest_file: ${testspace_dir}/para0.json
    regex_patterns:
      - '^(?!.*(\(|\)|«|»|\[|\])).*$'

  - _target_: sdp.processors.SubRegex
    input_manifest_file: ${testspace_dir}/para0.json
    output_manifest_file: ${testspace_dir}/para1.json
    text_key: text
    regex_params_list:
      - {"pattern": "[^.!?]*\\(([^)]*)\\)[^.!?]*", "repl": "\\1"}
      - {"pattern": "[^.!?]*\\[([^\\]]*)\\][^.!?]*", "repl": "\\1"}
      - {"pattern": "[^.!?]*«([^»]*)»[^.!?]*", "repl": "\\1"}
  
  - _target_: sdp.processors.SplitLineBySentence
    text_key: text
    end_pattern: ':|\.|…'
    input_manifest_file: ${testspace_dir}/lines1.json
    output_manifest_file: ${testspace_dir}/sentences0.json

  - _target_: sdp.processors.CreateCombinedManifests
    manifest_list: ["${testspace_dir}/para1.json", "${testspace_dir}/sentences0.json"]
    output_manifest_file: ${testspace_dir}/sentences_combined.json

  - _target_: sdp.processors.DropIfRegexMatch
    input_manifest_file: ${testspace_dir}/sentences_combined.json
    # input_manifest_file: ${testspace_dir}/sentences0.json
    output_manifest_file: ${testspace_dir}/sentences1.json
    regex_patterns:
      - '[0-9]'
      - '\('
      - '\)'
      - '\['
      - '\]'
      - '\*'
      - '"'
      - '[А-Яа-я]'
      - '[A-Za-z]'
      - '\+'
      - '='
      - '¬'
      - '&'

  # - _target_: sdp.processors.DropIfRegexMatch
  #   input_manifest_file: ${testspace_dir}/sentences0.json
  #   output_manifest_file: ${testspace_dir}/numbers.json
  #   regex_patterns:
      # - '[0-9]'
      # - '\('
      # - '\)'
      # - '\['
      # - '\]'
      # - '\*'
      # - '"'
      # # - '«'
      # # - '»'
      # - '[А-Яа-я]'
      # - '[A-Za-z]'
      # - '\+'
      # - '='
      # - '¬'
      # - '&'
      # # - '^(?!.*\().*$'
      # # - '^(?!.*\)).*$'
      # # - '^(?!.*[А-Яа-я]).*$'
      # # - '^(?!.*[A-Za-z]).*$'
      # - '^(?!.*«).*$'
      # - '^(?!.*»).*$'
      # # - '^(?![^0-9]*[0-9]).*$'
      # # - '[А-Яа-я]'
      # # - '[A-Za-z]'
      # # - '\+'
      # # - '='
      # # - '¬'
      # # - '&'
      # # - '[0-9]'
      # # - '^(?!.*\+).*$'
      # # - '^(?!.*=).*$'
      # # - '^(?!.*¬).*$'
      # # - '^(?!.*&).*$' 

  - _target_: sdp.processors.CountNumWords
    input_manifest_file: ${testspace_dir}/sentences1.json
    output_manifest_file: ${testspace_dir}/sentences2.json
    alphabet: "ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖՈՒԵ աբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆուև"
    text_key: text
    num_words_key: num_words

  - _target_: sdp.processors.PreserveByValue
    input_manifest_file: ${testspace_dir}/sentences2.json
    output_manifest_file: ${testspace_dir}/sentences3.json
    input_field: num_words
    target_value: 20
    operator: le

  - _target_: sdp.processors.PreserveByValue
    input_manifest_file: ${testspace_dir}/sentences3.json
    output_manifest_file: ${testspace_dir}/tasks.json
    input_field: num_words
    target_value: 3
    operator: ge

