documentation: |
  Wikipedia
processors_to_run: all
workspace_dir: ???
data_split: dev
final_manifest: ${workspace_dir}/${data_split}_manifest.json

processors:
  - _target_: sdp.processors.CreateInitialManifestWiki
    lang: "hy"
    raw_data_dir: ${workspace_dir}/raw_data

  - _target_: sdp.processors.CreateInitialManifestByExt
    raw_data_dir: ${workspace_dir}
    extension: txt
    output_file_key: source_filepath
    output_manifest_file: ${workspace_dir}/docfiles.json

  - _target_: sdp.processors.ReadTxtLines
    input_file_key: source_filepath
    text_key: text
    input_manifest_file: ${workspace_dir}/docfiles.json
    output_manifest_file: ${workspace_dir}/wiki_lines.json

  - _target_: sdp.processors.SubRegex
    input_manifest_file: ${workspace_dir}/wiki_lines.json
    output_manifest_file: ${workspace_dir}/wiki_lines1.json
    text_key: text
    regex_params_list:
      - {"pattern": '։', "repl": ':'}
      - {"pattern": '․', "repl": "."}
      - {"pattern": '—', "repl": "-"}
      - {"pattern": '–', "repl": "-"}
      - {"pattern": '―', "repl": "-"} 
      - {"pattern": '\.\.\.', "repl": "…"}
      - {"pattern": "\\s+", "repl": " "}
  
  - _target_: sdp.processors.SplitLineBySentence
    text_key: text
    end_pattern: ':|\.|…'
    input_manifest_file: ${workspace_dir}/wiki_lines1.json
    output_manifest_file: ${workspace_dir}/sentences0.json

  - _target_: sdp.processors.DropIfRegexMatch
    input_manifest_file: ${workspace_dir}/sentences0.json
    # output_manifest_file: ${workspace_dir}/sentences1.json
    output_manifest_file: ${workspace_dir}/wiki_clear.json
    regex_patterns:
      - '[0-9]'
      - '\('
      - '\)'
      - '\['
      - '\]'
      - '\*'
      - '"'
      - '[А-Яа-я]'
      - '[A-Za-z]'
      - '\+'
      - '='
      - '¬'
      - '&'
      - '«'
      - '»'

  # - _target_: sdp.processors.DropDublicates
  #   drop_key: "text"
  #   input_manifest_file: ${workspace_dir}/sentences1.json
  #   output_manifest_file: ${workspace_dir}/wiki_clear.json