processors_to_run: "0:"
workspace_dir: ???
final_manifest: ${workspace_dir}/final_manifest.json

processors:
  - _target_: sdp.processors.CreateInitialManifestByExt
    raw_data_dir: ${workspace_dir}/mp3
    extension: mp3
    output_field: source_filepath
    output_manifest_file: ${workspace_dir}/manifest0.json

  - _target_: sdp.processors.FfmpegConvert
    output_manifest_file: ${workspace_dir}/manifest1.json
    resampled_audio_dir: ${workspace_dir}/audio
    target_samplerate: 16000
    target_nchannels: 1
    input_field: "source_filepath"
    output_field: "audio_filepath"
    key_field: null

  - _target_: sdp.processors.GetAudioDuration
    audio_filepath_field: audio_filepath
    duration_field: duration
    output_manifest_file: ${workspace_dir}/manifest2.json
    
  - _target_: sdp.processors.ASRWhisper
    output_manifest_file: ${workspace_dir}/manifest3.json
    pretrained_model: "large-v2"
    output_text_field: text

  - _target_: sdp.processors.ASRTransformer
    output_manifest_file: ${workspace_dir}/manifest4.json
    pretrained_model: "distil-whisper/distil-large-v2" #"openai/whisper-large-v3"
    output_text_field: pred_text

  - _target_: sdp.processors.SubMakeLowercase
    output_manifest_file: ${workspace_dir}/manifest5.json
    text_key: "text"

  - _target_: sdp.processors.DropNonAlphabet
    output_manifest_file: ${workspace_dir}/manifest6.json
    alphabet: "ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖՈՒԵ աբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆուև.,!?"
    test_cases:
      - {input: {text: "test тест Գրիմ եղբայրներ, անտառի տնակը, Ռուսերենից թարգմանեց, Ամալիյա Ուկասյանը."}, output: null}
      - {input: {text: "Գրիմ եղբայրներ, անտառի տնակը, Ռուսերենից թարգմանեց, Ամալիյա Ուկասյանը."}, output: {text: "Գրիմ եղբայրներ, անտառի տնակը, Ռուսերենից թարգմանեց, Ամալիյա Ուկասյանը."}}

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${final_manifest}
    regex_params_list:
      - {"pattern": '\[(.*?)\]', "repl": ' '}
      - {"pattern": 'a', "repl": "ա"}
      
      - {"pattern": 'անտար', "repl": "անտառ"}
      - {"pattern": 'թնակ', "repl": "տնակ"}
      - {"pattern": 'Ռուսերենիս', "repl": "Ռուսերենից"}
      - {"pattern": 'ամալիահ', "repl": "Ամալիյա"}

      - {"pattern": 'Էտկարպո', "repl": "Էդգար Պո"}
      - {"pattern": 'թարգմանություն', "repl": "թարգմանությունը"}
      - {"pattern": 'արտաշ է սեմինի', "repl": "Արտաշես Էմինի"}
      # double space to single space
      - {"pattern": "\\s+", "repl": " "}
    test_cases:
      - {input: {text: "Գրիմ եղբայրներ, անտարի թնակը, Ռուսերենիս թարգմանեց, ամալիահ Ուկասյանը."}, output: {text: "Գրիմ եղբայրներ, անտառի տնակը, Ռուսերենից թարգմանեց, Ամալիյա Ուկասյանը."}}
      - {input: {text: "Էտկարպո, Մատնիչ սիրտը, թարգմանություն արտաշ է սեմինի."}, output: {text: "Էդգար Պո, Մատնիչ սիրտը, թարգմանությունը Արտաշես Էմինի."}}
