documentation: |
  Toloka Armenian

processors_to_run: all
workspace_dir: ???
API_KEY: "QBiiuByvLaYu1llgZjDFXw.045e.f1bcUbqp_4Q5ENwt9-_NdCNjZpQspNFAwnm1qXPj-Y24DyjVuxPhP4nu7DKoxuZgiZvvfWalAZ4uIb3o4ztD0kt8jNP4sW4k8tp_8m3JwUQ" # SANDBOX
# API_KEY: "1V0v8tbFtwPhDVMbN3cvcQ.045e.k93FVRUudCOHplT6OHcDNjc-k8V_rSFr8l5_jLyo4rLT9W4fgabM40EyompNakPZ0uU-_sgc0hKHzrEge5AJNy5MwZCu93BHoTJGOS1lwqE"  # PRODUCTION

processors:
  - _target_: tolokan_validation.processors.WhiteNoiseManifestGenerator
    input_manifest_file: ${workspace_dir}/evnmag_data_collection_resultsevn_mag_manifest.json
    output_manifest_file: ${workspace_dir}/white_noize_manifest.json
    output_dir: ${workspace_dir}/white_noize

  - _target_: sdp.processors.CreateInitialManifestMCVNew  # apt-get update # apt-get upgrade # apt-get install sox libsox-fmt-all
    output_manifest_file: ${workspace_dir}/mcv_manifest.json
    language_id: cv-corpus-17.0-delta-2024-03-15-hy-AM
    extract_archive_dir: ${workspace_dir}/raw
    resampled_audio_dir: ${workspace_dir}/16k
    data_split: validated
    raw_data_dir: ${workspace_dir}
    
  - _target_: tolokan_validation.processors.MCVNoizeManifestGenerator
    input_manifest_file: ${workspace_dir}/mcv_manifest.json
    output_manifest_file: ${workspace_dir}/mcv_noize_manifest.json
    output_dir: ${workspace_dir}/mcv_noize
    limit: 100

  - _target_: sdp.processors.CreateCombinedManifests
    manifest_list: ["${workspace_dir}/white_noize_manifest.json", "${workspace_dir}/mcv_noize_manifest.json"]
    output_manifest_file: ${workspace_dir}/control_tasks.json