documentation: |
  Tarteel AI's Everyayah
  ###################################

  The config performs the following data processing.
  1. Drops any data that contains symbols not in the supported alphabet.
  2. Can be used to remove punctuation and diacritical marks.
  3. Can be used to replace positional forms of Arabic letters with general unicodes.
  4. Can be used to normalize Arabic ligatures.

  **Required arguments**.

  * **raw_dataset_dir**:  path to the tarred dataset.
  * **workspace_dir**:    specify the workspace folder where all audio files will be stored.
  * **data_split**:       should be "train", "validation", "test".
  * **remove_punctuation**: specify whether to remove punctuation or not. Should be "True" or "False". Defaults to False.
  * **remove_diacritics**: specify whether to remove tatweel marks or not. Should be "True" or "False". Defaults to True.
  * **remove_tatweel**: specify whether to remove punctuation or not. Should be "True" or "False". Defaults to True.
  * **normalize_ligature**: specify whether to normalize ligature or not. Should be "True" or "False". Defaults to True.
  * **apply_nfkc**: Applies NFKC normalization to the text. Find more here https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize.
    Defaults to True.
  * **min_duration**: minimal duration of segment in seconds. Defaults to 0.1s.
  * **max_duration**: maximal duration of segment in seconds. Defaults to 20s.

  **Output format**.

  This config dumps the final manifest at ``${workspace_dir}/${data_split}/manifest.json`` and wav files ``${workspace_dir}/${data_split}/audios``.
  The output manifest contains the following fields:

  * **audio_filepath (str)**: relative path to the audio files.
  * **text (str)**: transcription.
  * **duration (float)**: audio duration in seconds.

processors_to_run: "0:"

data_split: test # specify dataset type (clean_train, clean_test, ...)
workspace_dir: ???

min_duration: 0.1 # minimal duration of the segment
max_duration: 20.0 # maximal duration of the segment

raw_data_dir: ${workspace_dir} 
already_downloaded: True

remove_punctuation: False
remove_diacritics: True
remove_tatweel: True
normalize_ligature: True
apply_nfkc: True

final_manifest: ${workspace_dir}/${data_split}/manifest.json

processors:
  # 0 creating manifest {sample_id, audio_path}
  - _target_: sdp.processors.CreateInitialManifestHuggingFace
    dataset_name: tarteel-ai/everyayah
    data_split: ${data_split}
    target_samplerate: 16000
    resampled_audio_dir: ${workspace_dir}/${data_split}/audios
    raw_data_dir: ${raw_data_dir}
    already_downloaded: ${already_downloaded}
    output_manifest_file: ${workspace_dir}/${data_split}/manifest0.json

  # 1 Dropping too short and too long segments
  - _target_: sdp.processors.DropHighLowDuration
    high_duration_threshold: ${max_duration}
    low_duration_threshold: ${min_duration}
    duration_key: duration
    output_manifest_file: ${workspace_dir}/${data_split}/manifest1.json

  # 2 removing punctuation, diacritics, dotted letters and tatweel
  - _target_: sdp.processors.langs.arabic.ArabicTextPreprocessor
    input_text_key: text
    remove_diacritics: ${remove_diacritics}
    remove_punctuation: ${remove_punctuation}
    remove_tatweel: ${remove_tatweel}
    normalize_ligature: ${normalize_ligature}
    apply_nfkc: ${apply_nfkc}
    output_manifest_file: ${workspace_dir}/${data_split}/manifest2.json

  # 3 dropping non alphabetical symbols
  - _target_: sdp.processors.DropNonAlphabet
    alphabet: " \u0631\u0630\u062F\u062E\u062D\u062C\u062B\u062A\u0629\u0628\u0627\u0626\u0625\u0624\u0623\u0622\u0621\u064A\u0649\u0648\u0647\u0646\u0645\u0644\u0643\u0642\u0641\u063A\u0639\u0638\u0637\u0636\u0635\u0634\u0633\u0632\u064B\u064C\u064D\u064E\u064F\u0650\u0651\u0652"
    output_manifest_file: ${final_manifest}
