name: Docker Build and Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t sdp-test-image:${{ github.sha }} -f docker/Dockerfile .
      
    - name: Run test tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          sdp-test-image:${{ github.sha }} \
          bash -c "python -m pytest tests/test_utils.py -v"
    
    - name: Get test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          pytest.xml
          coverage.xml