name: Granary pipeline E2E test

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  granary-e2e-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/main.txt
        pip install -r requirements/tests.txt
        sudo apt-get update
        sudo apt-get install -y libsndfile1 ffmpeg sox libsox-fmt-mp3
        pip install pytorch_lightning
        pip install Cython wheel  # need to pre-install to avoid error in nemo installation
        pip install nemo-toolkit[common]==2.2.1
        pip install pymarian
        python -m pip cache purge
        
    - name: Run Granary E2E test
      env:
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        CLEAN_UP_TMP_PATH: 1
        USE_THREADING_BACKEND: 1
      run: |
        python -m pytest tests/test_granary_pipeline_end_to_end.py tests/test_data_to_data.py